[package]
name = "virtue"
version = "0.0.18"
edition = "2021"
description = "A sinless derive macro helper"
license = "MIT"
documentation = "https://docs.rs/virtue"
repository = "https://github.com/bincode-org/virtue"
readme = "README.md"

[workspace]
members = ["test", "test/derive"]
