[package]
name = "virtue-next"
version = "0.1.2"
edition = "2024"
description = "A sinless derive macro helper"
license = "MIT or Apache-2.0"
documentation = "https://docs.rs/virtue"
repository = "https://github.com/Apich-Organization/virtue"
readme = "README.md"

[dev-dependencies]
proc-macro2 = "1.0"

[dependencies]
proc-macro2 = { version = "1.0", optional = true }

[workspace]
members = ["test", "test/derive"]

[profile.bench]
codegen-units = 1
debug = 1
lto = true

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
strip = true

[profile.dev]
lto = false
opt-level = 0
debug = true
